management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085
  http2:
    enabled: true
  tomcat:
    redirect-context-root: false

spring:
  boot:
    admin:
      client:
        url: http://dell-4290.local:8099
        auto-deregistration: true
        instance:
          prefer-ip: true
          service-base-url: http://weather.gpc4j.org
  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion: non_null

joinfaces:
  jsf:
    state-saving-method: client

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss.SSS,America/Los_Angeles

