name: delete branch on close pr
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Substitute Secrets
        run: |
          sed -e 's/KUBE_SERVER/${{ secrets.KUBE_SERVER }}/g' kube_config > config.1
          sed -e 's/KUBE_TOKEN/${{ secrets.KUBE_TOKEN }}/g' config.1 > k_config
          cat k_config
          # Set hostname to just Application name for master branch
          sed -e "s/HOSTNAME/${APP_NAME}/g" weather-template.yaml > weather.yaml

      - name: Display Config
        run: cat k_config

      - name: Delete Namspace
        env:
          KUBECONFIG: ./k_config
        run: |
          kubectl delete namespace ${APP_NAME}-${GITHUB_REF##*/}

